name: Cherry-pick

on:
  pull_request:
    branches:
      - main
    types: ["labeled"]

jobs:
  cherry_pick_release:
    permissions:
      pull-requests: write
      statuses: read
      contents: write
    runs-on: ubuntu-latest
    name: Cherry pick into release
    if: ${{ contains(github.event.pull_request.labels.*.name, 'cherry-pick release') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cherry pick into release 1
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release-v2.0
          labels: |
            cherry-pick
          reviewers: |
            aver1cal
          title: '[cherry-pick] {old_title}'
          body: 'Cherry-pick of #{old_pull_request_id}'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}