name: Cherry-pick

on:
  pull_request:
    branches:
      - main
    types: ["labeled"]

jobs:
  cherry_pick_release:
    permissions:
      pull-requests: write
      statuses: read
      contents: write
    runs-on: ubuntu-latest
    name: Cherry pick into release
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cherry pick into release
        uses: Xealth/cherry-pick-action@v1.1.0
        with:
          allowUserToSpecifyBranchViaLabel: 'true'
          labelPatternRequirement: 'cherry-pick release'
          userBranchPrefix: 'release-'
          labels: |
            cherry-pick
          title: '[cherry-pick] ${{ github.event.pull_request.title }}'
          body: 'cherry-pick of ${{ github.event.pull_request.ref }}'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}