name: Cherry-pick

on:
  workflow_dispatch:
    branches:
      - main
      - master
      - develop
    inputs:
      release-tag:
        description: Release tag
        type: string
        required: true

jobs:
  cherry_pick_release:
    runs-on: ubuntu-latest
    name: Cherry pick into release
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cherry pick into release
        uses: Xealth/cherry-pick-action@v1.1.0
        with:
          allowUserToSpecifyBranchViaLabel: 'true'
          labelPatternRequirement: 'cherry-pick v'
          userBranchPrefix: 'v'
          labels: |
            cherry-pick
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}