name: Cherry-pick
on:
  pull_request:
    branches:
      - main
    types: ["labeled"]
jobs:
  cherry_pick_release:
    permissions:
      pull-requests: write
      statuses: read
      contents: write
    runs-on: ubuntu-latest
    name: Cherry pick into release
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cherry pick into release
        uses: aver1cal/cherry-pick-action@v1.0.2
        with:
          allowUserToSpecifyBranchViaLabel: 'true'
          labelPatternRequirement: 'cherry-pick release'
          userBranchPrefix: 'release-'
          body: 'cherry-pick of ${{ github.event.pull_request.html_url }}'
          labels: |
            cherry-pick
          reviewers: |
            aver1cal
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}